spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      maxFileSize: 30Mb
      maxRequestSize: 30Mb

  #redis
  # database:0
  # host:127.0.0.1
  # port:6379
  # password:

  devtools:
    restart:
      enabled: true
  mvc:
    locale: zh_CN
    locale-resolver: fixed
    static-path-pattern: /static/**
  aop:
    auto: true
    proxy-target-class: true
  messages:
    basename: i18n/message

  # spring boot admin
  application:
    name: Basics Service
  boot:
    admin:
      client:
        url: "http://localhost:8000"

###################################################################
###Mybatis (MybatisAutoConfiguration)
###################################################################
##mybatis-plus mapper xml 文件地址
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  ##mybatis-plus type-aliases 文件地址
  type-aliases-package: cn.gatherlife.basics.model
  #主键类型 0：“数据库ID自增”, 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
  global-config:
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #逻辑删除配置
    logic-delete-value: -1
    logic-not-delete-value: 0
    #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
